version: "3.8"

x-services-volumes: &service-volumes

x-database-variables: &database-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres

services:
  website:
    image: website-portfolio:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: *database-variables
